version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: http://host.docker.internal:7890
        HTTPS_PROXY: http://host.docker.internal:7890
        NO_PROXY: localhost,127.0.0.1
    volumes:
      - ..:/workspace:cached
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Ensure the container uses the proxy
    environment:
      HTTP_PROXY: http://host.docker.internal:7890
      HTTPS_PROXY: http://host.docker.internal:7890
      NO_PROXY: localhost,127.0.0.1
